### PR TITLE
FIX: Make node-bitcoin compatable with browserify

### PR DESCRIPTION
**Pull request by brandonrobertz**
I have some isomorphic JS that currently uses node-bitcoin. It works beautifully inside node. When I browserify it, the replacement `http` module that provides the `request` object, doesn't have a `setTimeout` method, which causes a crash. This is a simple two-line fix that allows this library to work in the browser, as well.

### CODE REVIEW

**Comment by freewil** [comment]
wouldn't a better solution be to send a pull request to http-browserify?

**Comment by brandonrobertz** [comment]
That would be cleaner on this end. I guess I can give that a shot first if you'd prefer. But with 25 open pull requests and an existing issue about setTimeout from 8 months ago with zero comments, I'm not sure how far I'll get.

**Comment by brandonrobertz** [comment]
I commented on https://github.com/substack/http-browserify/issues/49 to see there's any interest in a fix for this upstream.

**Comment by dcousens** [comment]
@freewil it would be cleaner.   Alternatively you could use something like https://github.com/scottcorgan/httpify

**Comment by brandonrobertz** [comment]
I'm going to close this ticket and focus on patching http-browserify.

**Pull request closed without merging**
