### PR TITLE
Added Promise support to commands. If no callback function is provide…

### PR DESCRIPTION
**Pull request by rcorbish**
…d, a Promise is returned. The Promise will only support the data returned (no headers)

I added support to return Promises when no callback is present. The code is 100% backwards compatible

example ...

var client = new bitcoin.Client({
	  host: 'rcorbish.ydns.eu',
	  port: 18332,
	  user: 'bitcoinrpc',
	  pass: 'password',
	  timeout: 30000
	});

// As a Promise
client.getInfo()
.then(function(data) {
	console.log('get Info - Promise' );
	console.log( data ) ;
} )
.catch(function(err) {
	console.log( err ) ;
} ) ;

// Original callback means
client.getInfo( function(err, data, resHeaders) {
	console.log('get Info - Original' );
	  if (err) return console.log(err);
	  console.log(data);
	});

### CODE REVIEW

**Comment by freewil** [comment]
Are there any popular Node.js modules out there that support promises as an alternative API like this?

**Comment by rcorbish** [comment]
Quite a few. I used the standard  [Promise] (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise) version. There are other packages defined outside the language.

BTW: your package is extremely useful - simple and elegant

The chaining can be very useful (to avoid callback nesting) - example 


	var promiseAddr1 = client.dumpPrivKey( addr1 ) ;
	var promiseAddr2 = client.dumpPrivKey( addr3 ) ; 
	
	var promiseRawTx  = client.createRawTransaction( [ { txid: msigTxid, vout:0,
						scriptPubKey:redeemPubKey,
						redeemScript:redeemScript}],
						{ mvkgqz.......zf7Bng2XWQT : 1.1 } ) ;
	
	Promise.all( [ promiseRawTx, promiseAddr1, promiseAddr2 ] )
	.then(function( data ) {
		var rawTx = data[0] ;
		return client.signRawTransaction( rawTx, [ { txid: msigTxid, vout:0,
			scriptPubKey:redeemPubKey,
			redeemScript:redeemScript}], [data[1], data[2] ] ) ;
	} )
	.then(function( signedTx ) {
		return client.sendRawTransaction( signedTx.hex ) ;
	} )
	.then(function( data ) {
		console.log( "Sent TXID:", data ) ;
	} )
	.catch(function(err) {
		console.log( "E R R O R", err ) ;
	} ) ;

**Comment by freewil** [comment]
I'm hesitant to merge this in, what if you created a promise-based wrapper around this module? I'd be happy to mention it and link over to it in the Readme.

**Comment by rcorbish** [comment]
Understood. I'll see what I can do.

Thanks

**Comment by rcorbish** [comment]
I created a new package https://www.npmjs.com/package/bitcoin-promise, as you suggested.

**Comment by freewil** [comment]
Awesome :tada:. I added a mention in the readme in 33d4ff907948d666b9ca331c3d1cd2fe4a17ee4f

**Comment by rcorbish** [comment]
Thank-you, that's really nice of you. Take care...

**Pull request closed without merging**
